language: python
sudo: required
dist: bionic
cache: pip

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

before_install:
  - pip install --quiet coverage flake8 pyyaml

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
